# 1. Notifications
notifications:
  slack:
    rooms:
      - secure: "wU4Z5NIwO5vS/gJj4S8Ccs5gG3xYRk6AzjblIUi02O7xDDBClmzjPqfgfHvvkNgsoEZhN0skuWC8mveQMMQ2k3TxlMUaVFNxW8dGOBf5T9x0KCbpNXHNkly29cW2GZOTU5qn4lHbMRljx3v98GRSNUIqMTxz7cJFS9YpqaSpnHPS/JVDtnjYU7bh4VHk+e+zL+Lgsme1mOi6JvP1Bufpj5MaTZ0LzfXuFPtK4SBcGbATdMd1iZ0NTIGkEqgOWjJ9qICJaqXLnX4qw4xtfYf5yYM41ig1s0YeArTifJ3qM03/ThfxccdwG3GKt7dhg5HhdCQRrWmxrnsErOCN481skCCSH7w3Hl6AMiN0w3W24D3E9kt88MARHj7mcEyQ0m0h8i/heP8vze2WFVAYYBiPjt27aGL6yKe0ljGp+E3HocU2xp06aZ7EmXzCeUV2sqv2KhzSbCwpCD7FLuFamDpmS4MlfQRc1bIMibOFb7YJkjDihbdT7sJ6kJ0N5xnmNc3HVZr+IolalV/imu/PHf8FktGLN4JGJGF+25udHKKPF3hl8MhMvzlZJdAmZq0NWl55Eb7V/Nh6awcyegbTJCMiWW7OW2Dk/dugPWHOwNjLMljWcJxF4C/mlXLfjpqeQChB7rgSk15or8okUrTIlplvJUAkOjmiElWcxVmmAPNIPA0=" # atex-ci
      - secure: "LPyzq0zWXKV4KrDp2leRf7y8jVbGVi73BznST6IFxunXLG8RYwj9pM2flsyIKnd/BLSyXz4YTw0SDSzrKFHlzJjDisgAwFuvWvydRHXzgIP+GFkgqho6yPIF/1FNu8rra/3X399BcAVZliWX2cdVuHhWdNwOqjWPkY+KtWjdIcNQ8da+40FEyShK5YEZA3Opmm7lQvZRrCADbDi+ZKDhQcrxMiEjp7udx7Ve5U/R0PNC3ha9T1vjefnFYTWORxufSGpKzROs7bphgaPceN1Lb9vc1jnd1yx3jyEhFoI3XiSQr+0m+uyHquklP4IPnx1jtJD0uGiW+HOMy9B1dMhr5JAajr0zY35vHT9cNHMPvY9kPV8Wz+hat7Fd6vHL/TGGOqyMwxIPV5fdSDu0P5iOVZ6rRfaqr/wGYzS2HVDOfmjssVT3XFiaf+qRZmEpgqbj4JKjgeQ4+t8lwkw4gHpXhnOlUm+/k3nBhNVEpi3CdpQha0SuGfOoOwGPSf+w4V7EHnZbTqV4/wFX68gB3WMq6/d/MlmqkNu/EU7qF7DxzATXhjr0F/YBaKMaPXAQ+MQjjSJDqhDRWoEBISiCSJcx/y0jJBKuzGn5F9o59yolxSIRS4RuD99kx90RvGj/zyIDmrBZFdAEOZDtcfN53zqSn/PBLEObD30jc5B06EK8ZLM=" # cloud-ci
    on_success: change
    on_pull_requests: false

# 2. Env
# env:

# 3. Git
# git:
branches:
  except:
    - /^f\// # feature branches require PR
    - /^v\d+\.\d+\.\d+$/ # npm-publish-tag

# 4. Bootstrap
os: linux
dist: trusty
sudo: false
language:
  - node_js
node_js:
  - node
# addons:
before_cache: ./.travis.sh before_cache
cache:
  directories:
    - $HOME/.local
    - $HOME/.npm
    - $HOME/.pip-cache/
    - $HOME/Library/Caches/Homebrew
    - /tmp/support-firecloud.cache
    - node_modules

# 5. Steps
before_install: ./.travis.sh before_install
install: ./.travis.sh install
before_script: ./.travis.sh before_script
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

# 6. Deploy
before_deploy: ./.travis.sh before_deploy
# deploy:
after_deploy: ./.travis.sh after_deploy
